CMakeLists.txt ZXing is required by "src/core/CMakeLists.txt:19 (target_link_libraries)"
If zxing is not available, cmake configure returned:

CMake Warning at CMakeLists.txt:43 (find_package):
  By not providing "FindZXing.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "ZXing", but
  CMake did not find one.

  Could not find a package configuration file provided by "ZXing" (requested
  version 2.0) with any of the following names:

    ZXingConfig.cmake
    zxing-config.cmake

  Add the installation prefix of "ZXing" to CMAKE_PREFIX_PATH or set
  "ZXing_DIR" to a directory containing one of the above files.  If "ZXing"
  provides a separate development package or SDK, be sure it has been
  installed.

CMake Warning (dev) at /usr/share/ECM/kde-modules/KDEClangFormat.cmake:109 (add_custom_command):
  Exactly one of PRE_BUILD, PRE_LINK, or POST_BUILD must be given.  Assuming
  POST_BUILD to preserve backward compatibility.

  Policy CMP0175 is not set: add_custom_command() rejects invalid arguments.
  Run "cmake --help-policy CMP0175" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
Call Stack (most recent call first):
  CMakeLists.txt:56 (kde_clang_format)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The following OPTIONAL packages have been found:

 * OpenGL
 * Vulkan
 * Qt6MultimediaWidgets (required version >= 6.5)
 * Qt6Core (required version >= 6.6.0)
 * Qt6WidgetsTools (required version >= 6.8.3)
 * Qt6Widgets (required version >= 6.6.0)
 * Qt6DBusTools (required version >= 6.8.3)
 * Qt6QmlTools (required version >= 6.8.3)
 * XKB (required version >= 0.5.0), XKB API common to servers and clients., <http://xkbcommon.org>
 * WrapVulkanHeaders
 * Qt6CoreTools (required version >= 6.8.3)
 * Qt6GuiTools (required version >= 6.8.3)
 * Qt6Gui (required version >= 6.6.0)
 * Freetype
 * PkgConfig
 * Fontconfig

-- The following REQUIRED packages have been found:

 * ECM (required version >= 6.0)
 * Qt6 (required version >= 6.5)
 * KF6Crash (required version >= 6.0)
 * KF6WidgetsAddons (required version >= 6.13.0)
 * KF6CoreAddons (required version >= 6.13.0)
 * KF6KIO (required version >= 6.0)
 * KF6Purpose (required version >= 6.0)
 * KF6ConfigWidgets (required version >= 6.13.0)
 * KF6XmlGui (required version >= 6.0)
 * Gettext
 * KF6I18n (required version >= 6.0)
 * KF6 (required version >= 6.0)

-- The following OPTIONAL packages have not been found:

 * Qt6QmlCompilerPlusPrivateTools (required version >= 6.8.3)
 * ZXing (required version >= 2.0)

-- Configuring done (2.4s)
CMake Error at src/core/CMakeLists.txt:19 (target_link_libraries):
  Target "kodaskannacore" links to:

    ZXing::Core

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

-- Generating done (0.1s)
CMake Generate step failed.  Build files cannot be regenerated correctly.
Error: module kodaskanna: Child process exited with code 1